### ISSUE TITLE
Chewy 0.9.0 does not implement `chewy:reset:all`

### ISSUE THREAD

**Issue by mathieugagne** [nbulaj/capistrano-chewy#2]
Simply calling `chewy:reset` was good enough in 0.8.4 as well.

**Comment by nbulaj** [comment]
Hi @mathieugagne. Thanx for your comment. I will check and fix it in a few days!

**Comment by mathieugagne** [comment]
Working on a PR for you

**Comment by mathieugagne** [comment]
@nbulaj Any plans for a quick patch release?

**Comment by nbulaj** [comment]
Released on rubygems, try it (if service already cached it)
